import Head from "next/head";  
import {FaGithub, FaLinkedin} from "react-icons/fa";
import { BsFillMoonStarsFill } from "react-icons/bs";
import deved from "../public/profile.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import Image from "next/image";
import { useState } from "react";

export default function Home() {
const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Lin Latt | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between ">
            <h1 className="text-xl font-roboto font-bold dark:text-white">DevelopByLinLatt</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 font-roboto"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium font-roboto">
              Lin Latt
            </h2>
            <h3 className="text-2xl py-2 font-roboto dark:text-white">
              Full Stack Web Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 max-w-xl mx-auto md:text-xl font-roboto dark:text-white">
              A Young Passionate Web Developer, Experience of developing website, 
              content, and managing projects in College. Also nterested in setup 
              the computer hardware and software. And also interested in develop 
              front-end, back-end and database design etc. 
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <div>
                <FaGithub></FaGithub>
                <p className="text-sm font-bold text-center mt-2 text-blue-500"><a href="https://github.com/linlatt33?tab=repositories">See Detail</a></p>
              </div>
              <div>
                <FaLinkedin></FaLinkedin>
                <p className="text-sm font-bold text-center mt-2 text-blue-500"><a href="https://www.linkedin.com/in/lin-latt-446842193/">See Detail</a></p>
              </div>
            </div>
            <div className="relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 overflow-hidden mx-auto mt-20">
              <Image src={deved} layout="fill" objectFit="cover"/>
            </div>
          </div>
        </section>

        <section>
          <div className="text-center">
            <h3 className="text-3xl py-1 font-roboto font-bold dark:text-white">My Skills</h3>
          </div>

          <div className="lg:flex gap-10 justify-center">

            <div className="text-center shadow-lg p-20 rounded-xl my-10 dark:bg-white">
              <Image src={design} width={100} height={100}/>
              <h3 className="py-4 text-teal-600 font-bold">Front End Development</h3>
              <p className="text-gray-800 py-1">HTML5</p>
              <p className="text-gray-800 py-1">CSS3</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">ReactJs</p>
              <p className="text-gray-800 py-1">NextJs</p>
              <p className="text-gray-800 py-1">BootStrap</p>
              <p className="text-gray-800 py-1">Tailwind</p>
            </div>

            <div className="text-center shadow-lg p-20 rounded-xl my-10 dark:bg-white">
              <Image src={code} width={100} height={100}/>
              <h3 className="py-4 text-teal-600 font-bold">Back End Development</h3>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">C</p>
              <p className="text-gray-800 py-1">Django</p>
              <p className="text-gray-800 py-1">Spring Boot</p>
            </div>

            <div className="text-center shadow-lg p-20 rounded-xl my-10 dark:bg-white">
              <Image src={consulting} width={100} height={100}/>
              <h3 className="py-4 text-teal-600 font-bold">Additional Skills</h3>
              <p className="text-gray-800 py-1">Communication Skill</p>
              <p className="text-gray-800 py-1">Team Working Skill</p>
              <p className="text-gray-800 py-1">English Skill</p>
              <p className="text-gray-800 py-1">Research Skill</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 font-roboto font-bold dark:text-white">Portfolio</h3>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row">
            <div>
              <Image className="rounded-lg" src={web1}></Image>
              <p className="text-center font-roboto font-bold text-blue-600"><a href="https://lovercoffee.000webhostapp.com/">Coffee Shop Website</a></p>
            </div>
            <div>
              <Image className="rounded-lg" src={web2}></Image>
              <p className="text-center font-roboto font-bold text-blue-600"><a href="http://linlatt.pythonanywhere.com/">Travel Review Website</a></p>
            </div>
            <div>
              <Image className="rounded-lg" src={web3}></Image>
              <p className="text-center font-roboto font-bold text-blue-600"><a href="https://wonderfullmovies.000webhostapp.com/">Movie Website</a></p>
            </div>
            <div>
              <Image className="rounded-xl shadow-lg" src={web4}></Image>
              <p className="text-center font-roboto font-bold text-blue-600"><a href="http://luckygroup.96.lt/">PTI Generator Website</a></p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
